"""added composite index for userid and logged at

Revision ID: 1508eb4a150a
Revises: a26ff6042437
Create Date: 2026-05-30 11:03:07.369085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1508eb4a150a'
down_revision: Union[str, Sequence[str], None] = 'a26ff6042437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_calories_user_id_logged_at', 'calories', ['user_id', 'logged_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_calories_user_id_logged_at', table_name='calories')
    # ### end Alembic commands ###
