"""added some new user stuff

Revision ID: 3f43956f1966
Revises: a39dad080929
Create Date: 2026-05-23 13:23:20.846745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f43956f1966'
down_revision: Union[str, Sequence[str], None] = 'a39dad080929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_loss_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('average_daily_steps', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('goal_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_type')
    op.drop_column('users', 'average_daily_steps')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'weight_loss_rate')
    # ### end Alembic commands ###
