"""added indexing on calorie user_id

Revision ID: a26ff6042437
Revises: 3f43956f1966
Create Date: 2026-05-26 14:39:40.037497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26ff6042437'
down_revision: Union[str, Sequence[str], None] = '3f43956f1966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_calories_user_id'), 'calories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calories_user_id'), table_name='calories')
    # ### end Alembic commands ###
