"""add user onboarding fields

Revision ID: a39dad080929
Revises: 4beb45335d0a
Create Date: 2026-05-23 13:01:07.896883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39dad080929'
down_revision: Union[str, Sequence[str], None] = '4beb45335d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight_loss_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('activity_level', sa.String(), nullable=False))
    op.add_column('users', sa.Column('average_daily_steps', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('goal_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_type')
    op.drop_column('users', 'average_daily_steps')
    op.drop_column('users', 'activity_level')
    op.drop_column('users', 'weight_loss_rate')
    # ### end Alembic commands ###
